import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <ClerkProvider>

    <html lang="en">
      <body
        className={`${inter.className}`}>
          {/*header*/}
          <Header />
          <main className="bg-blue-50 text-black p-4 min-h-screen">
              {children} 
          </main>
      
        {/*footer*/}
        <footer className="bg-blue-50 text-black p-4 text-center">
          <div className="container mx-auto px-4 text-gray-700">
          <h1 className="text-2xl font-bold">FinWise</h1>
          <p className="text">&copy; {new Date().getFullYear()} FinWise. All rights reserved.</p>
          </div>
          
        </footer>
      </body>
    </html>
        </ClerkProvider>

  );
}
